### ISSUE TITLE
How do you handle OPTIONS requests with this sample guide?

### ISSUE THREAD

**Issue by voor** [spring-guides/gs-rest-service-cors#5]
I'm having trouble after adding authentication, where my OPTIONS preflight is being denied as unauthorized.  I'm unsure about where to add this into a Spring Boot app.  There seem to be a lot of solutions, but most of them focus on web.xml configurations.

**Comment by sdeleuze** [comment]
Indeed, with Spring Framework 4.1 and previous versions, you had to set DispatcherServlet `dispatchOptionsRequest` init parameter to `true` (as explained [here](http://stackoverflow.com/questions/9521690/how-to-handle-http-options-with-spring-mvc), including how to do this with JavaConfig).

I am not going to update the current guide, because I will shortly publish a complete rewrite based on Spring Framework 4.2 CORS support, where these requests are automatically dispatched without any need to configure something explicitly. You can follow https://github.com/spring-guides/gs-rest-service-cors/issues/6 in order to be notified when this will be done.

**Comment by voor** [comment]
Thank you!
